import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`container mx-auto bg-slate-50 bg-gradient-to-br from-indigo-100 from-10% via-indigo-50 via-30% px-2 md:px-4 ${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
